// Copyright (C) 2020-2021 Parity Technologies (UK) Ltd. & Centrality Investments Ltd
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! RPC API for Ethy.

#![warn(missing_docs)]

use ethy_gadget::notification::EthyEventProofStream;
use futures::{StreamExt, TryStreamExt};
use jsonrpc_core::futures::{
	future::Executor as Executor01, future::Future as Future01, sink::Sink as Sink01, stream::Stream as Stream01,
};
use jsonrpc_derive::rpc;
use jsonrpc_pubsub::{manager::SubscriptionManager, typed::Subscriber, SubscriptionId};
use log::warn;
use std::sync::Arc;

mod notification;

/// Provides RPC methods for interacting with Ethy.
#[allow(clippy::needless_return)]
#[rpc]
pub trait EthyApi<Notification> {
	/// RPC Metadata
	type Metadata;

	/// Returns event proofs generated by Ethy
	#[pubsub(subscription = "ethy_eventProofs", subscribe, name = "ethy_subscribeEventProofs")]
	fn subscribe_event_proofs(&self, metadata: Self::Metadata, subscriber: Subscriber<Notification>);

	/// Unsubscribe from receiving notifications about recently finalized blocks.
	#[pubsub(subscription = "ethy_eventProofs", unsubscribe, name = "ethy_unsubscribeEventProofs")]
	fn unsubscribe_event_proofs(
		&self,
		metadata: Option<Self::Metadata>,
		id: SubscriptionId,
	) -> jsonrpc_core::Result<bool>;
}

/// Implements the EthyApi RPC trait for interacting with Ethy.
pub struct EthyRpcHandler {
	event_proof_stream: EthyEventProofStream,
	manager: SubscriptionManager,
}

impl EthyRpcHandler {
	/// Creates a new EthyRpcHandler instance.
	pub fn new<E>(event_proof_stream: EthyEventProofStream, executor: E) -> Self
	where
		E: Executor01<Box<dyn Future01<Item = (), Error = ()> + Send>> + Send + Sync + 'static,
	{
		let manager = SubscriptionManager::new(Arc::new(executor));
		Self {
			event_proof_stream,
			manager,
		}
	}
}

impl EthyApi<notification::EventProof> for EthyRpcHandler {
	type Metadata = sc_rpc::Metadata;

	fn subscribe_event_proofs(&self, _metadata: Self::Metadata, subscriber: Subscriber<notification::EventProof>) {
		let stream = self
			.event_proof_stream
			.subscribe()
			.map(|x| Ok::<_, ()>(notification::EventProof::new(x)))
			.map_err(|e| warn!("Notification stream error: {:?}", e))
			.compat();

		self.manager.add(subscriber, |sink| {
			let stream = stream.map(|res| Ok(res));
			sink.sink_map_err(|e| warn!("Error sending notifications: {:?}", e))
				.send_all(stream)
				.map(|_| ())
		});
	}

	fn unsubscribe_event_proofs(
		&self,
		_metadata: Option<Self::Metadata>,
		id: SubscriptionId,
	) -> jsonrpc_core::Result<bool> {
		Ok(self.manager.cancel(id))
	}
}
