
[package]
name = "crml-nft-rpc"
version = "2.1.0"
authors = ["Centrality Developers <developers@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"

sp-api = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-rpc = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }

crml-nft = { path = "../" }
crml-nft-rpc-runtime-api = { path = "./runtime-api" }
cennznet-primitives = { path = "../../../primitives" }
