[package]
name = "crml-generic-asset-rpc"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "RPC interface for the generic asset module."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
serde = { version = "1.0.101", features = ["derive"] }
sc-client-db = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing", features = ["kvdb-rocksdb", "parity-db"] }
sp-api = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
sp-blockchain = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
sp-rpc = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
sp-runtime = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
crml-generic-asset = { path = "../" }
crml-generic-asset-rpc-runtime-api = { path = "runtime-api" }

[dev-dependencies]
substrate-test-runtime-client = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
sc-consensus = { git = "https://github.com/plugblockchain/plug-blockchain", branch = "ecdsa_testing" }
serde_json = "1.0.50"
