[package]
name = "ethy-gadget"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Centrality Devleopers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
futures = "0.3"
hex = "0.4"
log = "0.4"
parking_lot = "0.11"
thiserror = "1.0"

bitvec = "0.20"
codec = { version = "2.0.0", package = "parity-scale-codec", features = ["derive"] }
prometheus = { package = "substrate-prometheus-endpoint", git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7"}

cennznet-primitives = { path = "../primitives" }
sp-api = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-application-crypto = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-arithmetic = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-blockchain = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-consensus = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-core = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-keystore = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-runtime = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sp-utils = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }

sc-client-api = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sc-keystore = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sc-network = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
sc-network-gossip = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }

[dev-dependencies]
sc-network-test = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "v3.0.0-rc7" }
