# Conform to: https://wiki.parity.io/Substrate-Style-Guide
reorder_imports = true
hard_tabs = true
max_width = 120
# TODO: Re-enable once build pipeline OKs this
# license_template_path = "LICENSE_TEMPLATE"
