[package]
name = "crml-eth-wallet-rpc"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "RPC interface for the eth wallet module."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
crml-support = { path = "../../support" }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
serde = { version = "1.0.101", features = ["derive"] }
sc-client-db = { git = "https://github.com/cennznet/substrate", rev = "2db18f864ae2bb50e60e497b7ac2c521daf83af6", version = "0.10.0-dev", features = ["kvdb-rocksdb", "parity-db"] }
sp-api = { git = "https://github.com/cennznet/substrate", rev = "2db18f864ae2bb50e60e497b7ac2c521daf83af6" }
sp-blockchain = { git = "https://github.com/cennznet/substrate", rev = "2db18f864ae2bb50e60e497b7ac2c521daf83af6" }
sp-rpc = { git = "https://github.com/cennznet/substrate", rev = "2db18f864ae2bb50e60e497b7ac2c521daf83af6" }
sp-runtime = { git = "https://github.com/cennznet/substrate", rev = "2db18f864ae2bb50e60e497b7ac2c521daf83af6" }
crml-eth-wallet = { path = "../" }
crml-eth-wallet-rpc-runtime-api = { path = "runtime-api" }
