[package]
name = "crml-eth-wallet-rpc-runtime-api"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "Runtime API definition required by ethereum wallet RPC extensions."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
cennznet-primitives = { default-features = false, path = "../../../../primitives" }
crml-eth-wallet = { default-features = false, path = "../../" }
crml-support = { default-features = false, path = "../../../support" }
sp-api = { git = "https://github.com/cennznet/substrate", rev = "d05b61e9b948621416a3c6eea2e10fd2f1b62aba", default-features = false }
sp-std = { git = "https://github.com/cennznet/substrate", rev = "d05b61e9b948621416a3c6eea2e10fd2f1b62aba", default-features = false }

[features]
default = ["std"]
std = [
	"cennznet-primitives/std",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
]
