[package]
name = "cennznet-rpc-core-txpool"
authors = [ "Centrality Developers" ]
edition = "2018"
homepage = "https://cennz.net"
license = "GPL-3.0-only"
repository = "https://github.com/cennznet/cennznet/"
version = "0.6.0"

[dependencies]
ethereum = { version = "0.12.0", default-features = false, features = [ "with-codec" ] }
ethereum-types = "0.13.1"
jsonrpsee = { version = "0.13.0", features = ["server", "macros"] }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

fc-rpc-core = { git = "https://github.com/cennznet/frontier", branch = "polkadot-v0.9.23" }