[package]
name = "crml-generic-asset-rpc-runtime-api"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "Runtime API definition required by Generic Asset RPC extensions."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
crml-generic-asset = { default-features = false, path = "../../" }
sp-api = { git = "https://github.com/paritytech/substrate", rev = "85fa0ab80c3ceccf4bb98380d7833578aaf8815e", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", rev = "85fa0ab80c3ceccf4bb98380d7833578aaf8815e", default-features = false }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
]
