[package]
name = "crml-support"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://cennznet/cennznet"
description = "Common crml types and traits"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", default-features = false, features = ["derive"], optional = true}
primitive-types = {version = "0.10.1", default-features = false, features = ["impl-codec", "impl-serde"] }
sp-runtime = { git = "https://github.com/cennznet/substrate", rev = "e7e83d9e26abd57dc5d8c41badfe4b26080cbb0d", default-features = false }
sp-std = { git = "https://github.com/cennznet/substrate", rev = "e7e83d9e26abd57dc5d8c41badfe4b26080cbb0d", default-features = false }
frame-support = { git = "https://github.com/cennznet/substrate", rev = "e7e83d9e26abd57dc5d8c41badfe4b26080cbb0d", default-features = false }
frame-system = { git = "https://github.com/cennznet/substrate", rev = "e7e83d9e26abd57dc5d8c41badfe4b26080cbb0d", default-features = false }
impl-trait-for-tuples = "0.2.1"
# this isn't needed by this crate but we need to force `getrandom` to use this feature for wasm build
# TODO: remove in next substrate update (https://github.com/paritytech/substrate/pull/7831/commits/5a6e41e683f8a4844c0a735dcd08caabb2313f11)
getrandom = { version = "0.2", features = ["js"] }

[features]
default = ["std"]
std =[
	"codec/std",
	"serde/std",
	"primitive-types/std",
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
	"sp-std/std",
]