[package]
name = "crml-nft"
version = "1.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
repository = "https://github.com/cennznet/cennznet"
description = "CENNZnet NFT module"

[dependencies]
cennznet-primitives = { path = "../../primitives", default-features = false }
serde = { version = "1.0.101", optional = true } 
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false, features = ["derive"] }
sp-core ={ default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
sp-io ={ default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
sp-keyring = { optional = true, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
sp-runtime = { default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
sp-std = { default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
frame-support = { default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
frame-system = { default-features = false, git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }
frame-benchmarking = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5", default-features = false, optional = true }
prml-support = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5", default-features = false }
variant_count = "1.0.0"

[dev-dependencies]
prml-generic-asset = { git = "https://github.com/plugblockchain/plug-blockchain", rev = "2.0.5" }

[features]
migrate = []
default = ["std"]
std = [
	"cennznet-primitives/std",
	"prml-support/std",
	"codec/std",
	"serde",
	"sp-core/std",
	"sp-io/std",
	"sp-keyring",
	"sp-runtime/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
]
runtime-benchmarks = ["frame-benchmarking"]
