[package]
name = "crml-governance"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "A runtime module for decentralized governance of the CENNZnet protocol"

[dependencies]
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false }
serde = { version = "1.0.102", optional = true }
cennznet-primitives = { path = "../../primitives", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde/std",
	"cennznet-primitives/std",
	"sp-std/std",
	"frame-support/std",
	"frame-system/std",
]