[package]
name = "crml-nft-rpc-runtime-api"
version = "2.1.0"
authors = ["Centrality Developers <developers@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false, features = ["derive"] }
sp-api = { git = "https://github.com/cennznet/substrate", rev = "771dfdd046da2ce4f7b1865ac40ebe805a821521", default-features = false }
sp-std = { git = "https://github.com/cennznet/substrate", rev = "771dfdd046da2ce4f7b1865ac40ebe805a821521", default-features = false }
sp-runtime = { git = "https://github.com/cennznet/substrate", rev = "771dfdd046da2ce4f7b1865ac40ebe805a821521", default-features = false }
crml-nft = { path = "../../", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"

[features]
default = ["std"]
std = [
	"codec/std",
	"crml-nft/std",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
]
