[package]
name = "cennznet-rpc-txpool"
authors = [ "Centrality Developers" ]
edition = "2018"
homepage = "https://cennz.net"
license = "GPL-3.0-only"
repository = "https://github.com/cennznet/cennznet"
version = "0.6.0"

[dependencies]
jsonrpc-core = "18.0.0"
rlp = "0.5"
serde = { version = "1.0", features = [ "derive" ] }
sha3 = "0.9"

# Moonbeam
cennznet-rpc-core-txpool = { path = "../../../rpc-core/txpool" }
cennznet-primitives = { path = "../../../../primitives" }

# Substrate
frame-system = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sc-transaction-pool = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sc-transaction-pool-api = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sp-api = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sp-blockchain = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sp-io = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sp-runtime = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }
sp-std = { git = "https://github.com/cennznet/substrate", rev = "254219721084b533626ffa16b74c415771d46747" }

# Frontier
ethereum-types = "0.13.1"
fc-rpc = { git = "https://github.com/cennznet/frontier", rev = "9fac81fceb918665de2e25a1ff7d5398cb2f8aba" }
