[package]
name = "crml-governance-rpc"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://github.com/cennznet/cennznet"
description = "RPC interface for the governance module."

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0" }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive = "18.0.0"
serde = { version = "1.0.101", features = ["derive"] }
sc-client-db = { git = "https://github.com/paritytech/substrate", version = "0.10.0-dev", features = ["kvdb-rocksdb", "parity-db"] }
sp-api = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
sp-rpc = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
sp-runtime = { git = "https://github.com/paritytech/substrate", version = "4.0.0-dev" }
crml-governance = { path = "../" }
crml-governance-rpc-runtime-api = { path = "runtime-api" }
