[package]
name = "pallet-evm-precompiles-cennzx"
version = "2.0.0"
authors = ["Centrality Developers <support@centrality.ai>"]
edition = "2018"
repository = "https://github.com/cennznet/cennznet"

[dependencies]
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
codec = { version = "2.0.0", package = "parity-scale-codec", default-features = false }
fp-evm = { default-features = false, git = "https://github.com/paritytech/frontier", rev = "f508edbe6e2849461c2323da294fac1a90fda451" }
pallet-evm = { default-features = false, git = "https://github.com/paritytech/frontier", rev = "f508edbe6e2849461c2323da294fac1a90fda451" }
precompile-utils = { path = "../utils", default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "76522d7937ba94ff1becef4e4e3ca78e3e1de341", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "76522d7937ba94ff1becef4e4e3ca78e3e1de341", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "76522d7937ba94ff1becef4e4e3ca78e3e1de341", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "76522d7937ba94ff1becef4e4e3ca78e3e1de341", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", rev = "76522d7937ba94ff1becef4e4e3ca78e3e1de341", default-features = false }
num_enum = { version = "0.5.3", default-features = false }
pallet-evm-precompiles-erc20 = { path = "../erc20", default-features = false }
crml-support = { path = "../../crml/support", default-features = false }
cennznet-primitives = { path = "../../primitives", default-features = false }
ethabi = { version = "16.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"ethabi/std",
	"scale-info/std",
	"fp-evm/std",
	"pallet-evm/std",
	"pallet-evm-precompiles-erc20/std",
	"frame-support/std",
	"frame-system/std",
	"num_enum/std",
	"precompile-utils/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"cennznet-primitives/std",
	"crml-support/std",
]
