name: Coverage
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  issue_comment:
    types:
    - created

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'check coverage') }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-12-22
          target: wasm32-unknown-unknown
          default: true
          override: true
      # generate test coverage
      - name: cargo tarpaulin
        run: |
          cargo install cargo-tarpaulin
          SKIP_WASM_BUILD=1 cargo tarpaulin --avoid-cfg-tarpaulin --skip-clean --workspace --locked
      # upload coverage info
      - name: Coverage
        uses: codecov/codecov-action@v3.0.0
        with:
          fail_ci_if_error: true