#
# Configure slack notifications for CI job status
#
on:
  workflow_run:
    workflows:
    - "CI"
    types:
    - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: "status bot"
        SLACK_ICON_EMOJI: ":white_check_mark:"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "build success :deal_with_it_parrot:"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: "status bot"
        SLACK_ICON_EMOJI: ":x:"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "build failed :halp:"
