#
# Configure slack notifications for CI job status
#
on:
  workflow_run:
    workflows: ["CI", "Image Builder"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: "bot"
        SLACK_ICON_EMOJI: ":robot_face:"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "${{github.actor}}'s build for ${{github.head_ref }} succeeded :deal_with_it_parrot:"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: "bot"
        SLACK_ICON_EMOJI: ":robot_face:"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "${{github.actor}}'s build for ${{github.head_ref }} failed :halp:"
